language: clojure
sudo: false
lein: lein
script:
  - lein test

jdk:
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
